name: Sync Latest Clash YML
on:
  schedule:
    - cron: "0 0 * * *"  # 北京时间 每天早8点
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # ====================== 你的配置 ======================
      - name: Config
        run: |
          echo "SRC_REPO=free-nodes/clashfree" >> $GITHUB_ENV
          echo "SRC_BRANCH=main" >> $GITHUB_ENV
          echo "SRC_PATH=." >> $GITHUB_ENV
          echo "LOCAL_SAVE=nodes-latest.yml" >> $GITHUB_ENV

      # ======================================================

      - name: Get date
        run: |
          echo "TODAY=$(date +%Y%m%d)" >> $GITHUB_ENV
          echo "YESTERDAY=$(date -d '1 day ago' +%Y%m%d)" >> $GITHUB_ENV

      - name: Download latest file
        run: |
          URL1="https://raw.githubusercontent.com/${SRC_REPO}/${SRC_BRANCH}/${SRC_PATH}/clash${TODAY}.yml"
          if curl -L -f -o "${LOCAL_SAVE}" "$URL1"; then
            echo "✅ 下载成功"
            exit 0
          fi

          URL2="https://raw.githubusercontent.com/${SRC_REPO}/${SRC_BRANCH}/${SRC_PATH}/clash${YESTERDAY}.yml"
          curl -L -f -o "${LOCAL_SAVE}" "$URL2"

      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit & Push
        run: |
          git add .
          git commit -m "Auto update clash file"
          git push
